
on: [push, pull_request]
name: Tests
jobs:

    ubuntu-bionic:
      name: linux x86_64 ubuntu bionic
      runs-on: ubuntu-18.04
  
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            persist-credentials: false
  
      - name: Build Docker
        run: |
            sudo apt update && \
            sudo apt-get remove -y docker docker-engine docker.io containerd runc && \
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common python3 && \
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add && \
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
            sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io && \
            sudo docker build -t test_bionic -f Dockerfile.bionic .

      - name: Run Tests
        run: python3 -c "import sys; import pty; exit(int(pty.spawn(['sudo','docker','run','-it','--rm','test_bionic','pytest','-v','tests']) / 256));"
